ProyectoProgramacion5/ProyectoProgramacion5/Controllers/FunctionsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using ProyectoProgra5.DataBaseHelper;
using ProyectoProgra5.Models;
using System.Data;
using System.Diagnostics.Eventing.Reader;

namespace ProyectoProgra5.Controllers
{
    public class FunctionsController : Controller
    {

        // GET: FunctionsController
        public ActionResult AddCar()
        {
            DataBaseHelper.DataBaseWebHelper db = new DataBaseHelper.DataBaseWebHelper();
            List<Cars> Car = new List<Cars>();


            DataTable ds = db.Fill("GetCarsBrand", null);

            foreach (DataRow dr in ds.Rows)
            {
                Car.Add(new Cars
                {
                    Id = Convert.ToInt32(dr["BrandID"].ToString()),
                    Brand = dr["BrandName"].ToString()

                });
            }

            ViewBag.Cars = Car;
            return View();
        }

        public ActionResult UpdateVisit(int id)
        {
            DataBaseHelper.DataBaseWebHelper db = new DataBaseHelper.DataBaseWebHelper();
            List<Visits> Visit = new List<Visits>();

            List<MySqlParameter> param = new List<MySqlParameter>()
            {
                new MySqlParameter("pID", id),
            };
            DataTable ds = db.Fill("Get_Visit", param);

            foreach (DataRow dr in ds.Rows)
            {
                Visit.Add(new Visits
                {
                    VisitorID = Convert.ToInt32(dr["VisitorID"].ToString()),
                    VisitorName = dr["VisitorName"].ToString(),
                    VisitorLastName = dr["VisitorLastName"].ToString(),
                    VehicleBrand = dr["VehicleBrand"].ToString(),
                    VehiclePlate = dr["VehiclePlate"].ToString(),
                    VehicleColor = dr["VehicleColor"].ToString(),
                    ArrivalTime = Convert.ToDateTime(dr["ArrivalTime"].ToString()),
                    Person = Convert.ToInt32(dr["Person"].ToString())
                });
            }

            ViewBag.Visit = Visit;

            return View();

        }
        public ActionResult AddDelivery()
        {
            return View();
        }
        public ActionResult UpdateDelivery(int id)
        {
            DataBaseHelper.DataBaseWebHelper db = new DataBaseHelper.DataBaseWebHelper();
            List<Delivery> Delivery = new List<Delivery>();

            List<MySqlParameter> param = new List<MySqlParameter>()
            {
                new MySqlParameter("pID", id),
            };
            DataTable ds = db.Fill("GetDelivery", param);

            foreach (DataRow dr in ds.Rows)
            {
                Delivery.Add(new Delivery
                {
                    DeliveryID = Convert.ToInt32(dr["DeliveryID"].ToString()),
                    DeliveryName = dr["DeliveryName"].ToString(),
                    Person = Convert.ToInt32(dr["Person"].ToString())
       
         
                });
            }

            ViewBag.Delivery = Delivery;
            return View();
        }
        public ActionResult GetDelivery()
        {
            DataBaseHelper.DataBaseWebHelper db = new DataBaseHelper.DataBaseWebHelper();
            List<Delivery> Delivery = new List<Delivery>();

            
            DataTable ds = db.Fill("GetDeliverys", null);

            foreach (DataRow dr in ds.Rows)
            {
                Delivery.Add(new Delivery
                {
                    DeliveryID = Convert.ToInt32(dr["DeliveryID"].ToString()),
                    DeliveryName = dr["DeliveryName"].ToString(),
                    Person = Convert.ToInt32(dr["Person"].ToString())


                });
            }

            ViewBag.Delivery = Delivery;
            return View();
        }
        public ActionResult AddVisit(int PersonID)
        {
            DataBaseHelper.DataBaseWebHelper db = new DataBaseHelper.DataBaseWebHelper();
            List<Cars> Car = new List<Cars>();


            DataTable ds = db.Fill("GetCarsBrand", null);

            foreach (DataRow dr in ds.Rows)
            {
                Car.Add(new Cars
                {
                    Id = Convert.ToInt32(dr["BrandID"].ToString()),
                    Brand = dr["BrandName"].ToString()

                });
            }

            ViewBag.Cars = Car;
            ViewBag.Person = PersonID;
            return View();

        }

        // GET: FunctionsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

       

        public ActionResult GetVisit(int id)
        {
            
            DataBaseHelper.DataBaseWebHelper db = new DataBaseHelper.DataBaseWebHelper();
            List<Visits> Visit = new List<Visits>();
           
            List<MySqlParameter> param = new List<MySqlParameter>()
            {
                new MySqlParameter("pID", 1),
            }; 
            DataTable ds = db.Fill("Get_Visit", param);

            foreach (DataRow dr in ds.Rows)
            {
                Visit.Add(new Visits
                {
                    VisitorID = Convert.ToInt32(dr["VisitorID"].ToString()),
                    VisitorName = dr["VisitorName"].ToString(),
                    VisitorLastName = dr["VisitorLastName"].ToString(),
                    VehicleBrand  =  dr["VehicleBrand"].ToString(),
                    VehiclePlate = dr["VehiclePlate"].ToString(),
                    VehicleColor = dr["VehicleColor"].ToString(),
                    ArrivalTime = Convert.ToDateTime(dr["ArrivalTime"].ToString()),
                    Person = Convert.ToInt32(dr["Person"].ToString())
                }); 
            }

            ViewBag.Visit = Visit;

            return View();
        }
        public ActionResult GetMyVisits()
        {

            DataBaseHelper.DataBaseWebHelper db = new DataBaseHelper.DataBaseWebHelper();
            List<Visits> Visit = new List<Visits>();
            List<Visits> Visit1 = new List<Visits>();
            List<Visits> Visit2 = new List<Visits>();
            DataTable ds = db.Fill("GetVisits", null);
            DataTable ds1 = db.Fill("GetVisitsFav", null);
            DataTable ds2 = db.Fill("GetVisitsNormal", null);


            foreach (DataRow dr in ds.Rows)
            {
                Visit.Add(new Visits
                {
                    VisitorID = Convert.ToInt32(dr["VisitorID"].ToString()),
                    VisitorName = dr["VisitorName"].ToString(),
                    VisitorLastName = dr["VisitorLastName"].ToString(),
                    VehicleBrand = dr["BrandName"].ToString(),
                    VehiclePlate = dr["VehiclePlate"].ToString(),
                    VehicleColor = dr["VehicleColor"].ToString(),
                    ArrivalTime = Convert.ToDateTime(dr["ArrivalTime"].ToString()),
                    Person = Convert.ToInt32(dr["PersonID"].ToString())
                });
            }
            foreach (DataRow dr in ds1.Rows)
            {
                Visit1.Add(new Visits
                {
                    VisitorID = Convert.ToInt32(dr["VisitorID"].ToString()),
                    VisitorName = dr["VisitorName"].ToString(),
                    VisitorLastName = dr["VisitorLastName"].ToString(),
                    VehicleBrand = dr["VehicleBrand"].ToString(),
                    VehiclePlate = dr["VehiclePlate"].ToString(),
                    VehicleColor = dr["VehicleColor"].ToString(),
                    ArrivalTime = Convert.ToDateTime(dr["ArrivalTime"].ToString()),
                    Person = Convert.ToInt32(dr["PersonID"].ToString())
                });
            }
            foreach (DataRow dr in ds2.Rows)
            {
                Visit2.Add(new Visits
                {
                    VisitorID = Convert.ToInt32(dr["VisitorID"].ToString()),
                    VisitorName = dr["VisitorName"].ToString(),
                    VisitorLastName = dr["VisitorLastName"].ToString(),
                    VehicleBrand = dr["VehicleBrand"].ToString(),
                    VehiclePlate = dr["VehiclePlate"].ToString(),
                    VehicleColor = dr["VehicleColor"].ToString(),
                    ArrivalTime = Convert.ToDateTime(dr["ArrivalTime"].ToString()),
                    Person = Convert.ToInt32(dr["PersonID"].ToString())
                });
            }

            ViewBag.Visit = Visit;
            ViewBag.VisitFav = Visit1;
            ViewBag.VisitNormal = Visit2;
            return View();
        }
        public ActionResult GetVisitsFav()
        {

            DataBaseHelper.DataBaseWebHelper db = new DataBaseHelper.DataBaseWebHelper();
            List<Visits> Visit = new List<Visits>();
            DataTable ds = db.Fill("GetVisitsFav", null);


            foreach (DataRow dr in ds.Rows)
            {
                Visit.Add(new Visits
                {
                    VisitorID = Convert.ToInt32(dr["VisitorID"].ToString()),
                    VisitorName = dr["VisitorName"].ToString(),
                    VisitorLastName = dr["VisitorLastName"].ToString(),
                    VehicleBrand = dr["VehicleBrand"].ToString(),
                    VehiclePlate = dr["VehiclePlate"].ToString(),
                    VehicleColor = dr["VehicleColor"].ToString(),
                    ArrivalTime = Convert.ToDateTime(dr["ArrivalTime"].ToString())
                    //Person = Convert.ToInt16(dr["Person"].ToString())
                });
            }
            return View(Visit);
        }

        public ActionResult GetVisitsNormal()
        {

            DataBaseHelper.DataBaseWebHelper db = new DataBaseHelper.DataBaseWebHelper();
            List<Visits> Visit = new List<Visits>();
            DataTable ds = db.Fill("GetVisitsNormal", null);


            foreach (DataRow dr in ds.Rows)
            {
                Visit.Add(new Visits
                {

ProyectoProgramacion5/ProyectoProgramacion5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using ProyectoProgra5.DataBaseHelper;
using ProyectoProgra5.Models;
using System.Collections;
using System.Data;
using System.Diagnostics;

namespace ProyectoProgra5.Controllers
{
    public class HomeController : Controller
    {
        /*private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }*/

        private readonly DataBaseWebHelper _dbHelper;

        public HomeController()
        {
            _dbHelper = new DataBaseWebHelper();
        }



        public ActionResult Profile(int personId)
        {
            var PersonList = GetPerson(personId);
            ViewBag.PersonList = PersonList;
            return View();
        }

        public ActionResult Index(List<Person> id)
        {
            ViewBag.Person = id;

            return View();
        }

        public ActionResult AdminView()
        {
            return View();
        }
        public ActionResult GuardView()
        {
            return View();
        }

        public IActionResult GetPersons()
        {
            string storedProcedure = "GetPerson";
            List<MySqlParameter> parameters = new List<MySqlParameter>();
            DataTable result = _dbHelper.Fill(storedProcedure, parameters);

            List<Person> people = new List<Person>();

            foreach (DataRow row in result.Rows)
            {
                Person person = new Person
                {
                    Id = Convert.ToInt32(row["Id"]),
                    Name = row["Name"].ToString(),
                    LastName = row["LastName"].ToString(),
                    PersonRol = Convert.ToInt32(row["PersonRol"]),
                    PersonUser = row["PersonUser"].ToString(),
                    PersonPassword = row["PersonPassword"].ToString(),
                    Vehicle = Convert.ToInt32(row["Vehicle"])
                };

                people.Add(person);
            }

            return View(people);
        }

        [HttpGet]
        public List<Person> GetPerson(int personId)
        {
            string storedProcedure = "GetPersonById";

            // Create a list to store parameters
            List<MySqlParameter> parameters = new List<MySqlParameter>();

            // Add the PersonId parameter
            parameters.Add(new MySqlParameter("@PersonId", personId));

            DataTable result = _dbHelper.Fill(storedProcedure, parameters);

            List<Person> persons = new List<Person>();

            foreach (DataRow row in result.Rows)
            {
                Person person = new Person
                {
                    Id = row["PersonID"] != DBNull.Value ? Convert.ToInt32(row["PersonID"]) : 0,
                    Name = row["PersonName"].ToString(),
                    LastName = row["PersonLastName"].ToString(),
                    Rol = row["RolName"].ToString(),
                    PersonUser = row["PersonUser"].ToString(),
                    Email = row["ContactEmail"].ToString(),
                    Phone = row["ContactPhone"].ToString(),
                    Condo = row["CondoName"].ToString(),
                    House = row["HouseID"] != DBNull.Value ? Convert.ToInt32(row["HouseID"]) : 0
                };

                persons.Add(person);
            }

            return persons;
        }


        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult About()
        {
           return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProyectoProgramacion5/ProyectoProgramacion5/Views/Home/GuardView.cshtml
@{
    ViewData["Title"] = "LandLock";
}
<nav class="navbar navbar-expand-lg bg-white">
    <div class="container-fluid">
        @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoPrograIV</a> *@
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active fs-4 fw-bold" aria-current="page" asp-controller="Home" asp-action="Index">LandLock</a>
                </li>
            </ul>
            <span class="navbar-text">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="btn dropdown-toggle" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">Funcionalidades</a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" asp-action="Visits" asp-controller="Functions">Ver visitas</a></li>
                                <li><a class="dropdown-item" asp-action="Reports" asp-controller="Functions">Reportes</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="About">Conocenos</a>
                    </li>

                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="btn dropdown-toggle" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="40" height="40" class="rounded-circle">
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                                <li><a class="dropdown-item" href="#">Dashboard</a></li>
                                <li><a class="dropdown-item" href="#">Edit Profile</a></li>
                                <li><a class="dropdown-item" href="#">Log Out</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </span>
        </div>
    </div>
</nav>



<div class="container-fluid">
    <div>
        <div class="row">
            <div class="col text-center">
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <h5>Sistema de Administración de Condominios</h5>
                ¡Bienvenido! Controla todas tus necesidades en tu condominio,<br>ahorra tiempo y siente la libertad de tu hogar 
                con <h4><b fs-4 style="color:#0068FF;">LandLock</b></h4>
            </div>
            <div class="col">
                <img src="https://concasa.life/n-images/isometric/MA-C.png" class="img-fluid" alt="...">
            </div>
        </div>
    </div>
</div>
<br />
<br />
<hr />
<br />
<br />
<div>
    <h4 class="text-center"><b>Funcionalidad</b></h4>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <h6>Reservación de áreas comunes</h6>
                            Con posibilidad de crear reglas de reserva que se ajustan a toda necesidad.
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col">
                            <h6>Registro de autorizados y visitas</h6>
                            Crea reglas para el ingreso de tus visitas, comparte invitaciones con Código QR para ingresos más rápidos y recibe notificaciones cuando ingresan y salen de tu casa.
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <img src="https://static.vecteezy.com/system/resources/previews/008/530/058/original/desktop-computer-mockup-cutout-file-png.png" class="img-fluid" alt="...">
                @*<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="https://dibujosycolores.com/letras/letra-a/letra-a-1.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="https://dibujosycolores.com/letras/letra-b/letra-b-1.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="https://dibujosycolores.com/letras/letra-c/letra-c-1.jpg" class="d-block w-100" alt="...">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>*@
            </div>
            <div class="col">
                <div class="container text-end">
                    <div class="row">
                        <div class="col">
                            <h6>Gestión de Cobro Inteligente</h6>
                            Hac aprende mes a mes de la manera en que lo utilizas, optimizando la gestión de cobro y disminuyendo el tiempo que debes invertir.
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col">
                            <h6>Notificaciones</h6>
                            Mensajería interna con el administrador, comunicados de la administración y notificaciones en tiempo real.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProyectoProgramacion5/ProyectoProgramacion5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "LandLock";
}

    <nav class="navbar navbar-expand-lg bg-white">
        <div class="container-fluid">
            @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoPrograIV</a> *@
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active fs-4 fw-bold" aria-current="page" asp-controller="Home" asp-action="Index">LandLock</a>
                    </li>
                </ul>
                <span class="navbar-text">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="btn dropdown-toggle" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">Funcionalidades</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                               
                                <li><a class="dropdown-item" asp-action="AddVisit" asp-controller="Functions" >Agregar Visita</a></li>
                                <li><a class="dropdown-item" asp-action="AddDelivery" asp-controller="Functions">Agregar Delibery</a></li>
                                <li><a class="dropdown-item" asp-action="AddCar" asp-controller="Functions" >Agregar Auto</a></li>
                                </ul>
                            </div>
                        
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="About">Conocenos</a>
                        </li>
                        
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="btn dropdown-toggle" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" width="40" height="40" class="rounded-circle">
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                                    <li><a class="dropdown-item" href="#">Dashboard</a></li>
                                <li><a class="dropdown-item" id="profileButton" href="#">Profile</a></li>
                                    <li><a class="dropdown-item" href="#">Log Out</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </span>
            </div>
        </div>
    </nav>

<div class="container-fluid">
    <div>
        <div class="row">
            <div class="col text-center">
                <br />
                <br />
                <br />
                <br />
                <h5>Sistema de Administración de Condominios</h5>
                ¡Bienvenido! Controla todas tus necesidades en tu condominio,<br>ahorra tiempo y siente la libertad de tu hogar 
                con <h4><b fs-4 style="color:#0068FF;">LandLock</b></h4>
            </div>
            <div class="col">
                <img src="https://concasa.life/n-images/isometric/MA-C.png" class="img" width="370" height="350">
            </div>
        </div>
    </div>
</div>
<br />
<br />
<hr />
<br />
<br />
<div>
    <h4 class="text-center"><b>Funcionalidad</b></h4>
    <div class="container">
        <div class="container overflow-hidden text-center">
            <div class="row gy-5">
                <div class="col-6">
                    <div class="p-3">
                        <div class="card" style="background-color: rgba(255, 255, 255, 0.05); border-color: rgba(255, 255, 255, 0.05);">
                            <div class="card-body">
                                <h6 class="card-title">Agenda visitas</h6>
                                <p class="card-text">Infomación de relevacia que nos permita identificar tus visitantes y mantener la seguridad del Condominio</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="p-3">
                        <div class="card" style="background-color: rgba(255, 255, 255, 0.05); border-color: rgba(255, 255, 255, 0.05);">
                            <div class="card-body">
                                <h6 class="card-title">Agregar vehiculos</h6>
                                <p class="card-text">Infomación de relevacia que nos permita identificar tus vehiculos y mantener la seguridad del Condominio</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="p-3">
                        <div class="card" style="background-color: rgba(255, 255, 255, 0.05); border-color: rgba(255, 255, 255, 0.05);">
                            <div class="card-body">
                                <h6 class="card-title">Visitas favoritas</h6>
                                <p class="card-text">Agrega a esas caras conocidas que son como parte de la familia</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <div class="p-3">
                        <div class="card" style="background-color: rgba(255, 255, 255, 0.05); border-color: rgba(255, 255, 255, 0.05);">
                            <div class="card-body">
                                <h6 class="card-title">Delivery</h6>
                                <p class="card-text">Registra tus pedidos con anticipación</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('profileButton').addEventListener('click', function () {
        // Get the current URL
        var currentUrl = window.location.href;

        // Extract the ID from the current URL
        var match = currentUrl.match(/[?&]personId=([^&]+)/);
        var dynamicId = match ? match[1] : null;

        // Generate the URL for the Profile page with the extracted ID
        var profileUrl = '@Url.Action("Profile", "Home")' + '?personId=' + dynamicId;

        // Navigate to the Profile page
        window.location.href = profileUrl;
    });
</script>